FROM debian
RUN apt-get update && \
    apt-get install -y nginx gettext-base && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY *.conf /etc/nginx/conf.d/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]