FROM debian
RUN apt-get update && \
    apt-get install -y nginx gettext-base && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY ./template-variables/10-variables.conf.template /etc/nginx/sites-available/app
RUN rm /etc/nginx/sites-available/default
RUN rm /etc/nginx/sites-enabled/default
EXPOSE 80
CMD ["/bin/bash", "-c", "envsubst < /etc/nginx/sites-available/app > /etc/nginx/sites-available/app && ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/app && nginx -g 'daemon off;'"]